common: &common
  adapter: postgresql
  username: postgres
  password: postgres
  host: localhost
  port: 5432

development:
  <<: *common
  database: ulab_development

test:
  <<: *common
  database: ulab_test

production:
  <<: *common
  database: ulab_production
